Adding support for custom Azure deployments
Azure-Samples/azure-search-openai-demo pull request #1273
Opened 2024-02-14 16:53 UTC by andredewes

## Purpose
Currently, the app only supports talking to Azure OpenAI endpoints directly, since it manually builds the URLs with suffix '*.openai.azure.com'. This won't allow any other Azure service like API Management to be a proxy or load balancer since we can't specify a custom URL.  
This PR allows the user to set the environment variable "OPENAI_HOST" to "azure_custom" and then you can define any custom URL by setting the "OPENAI_BASE_URL" variable. 
The managed identity is kept, which allows us to keep this integration keyless.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
```
- Run "azd env set OPENAI_HOST azure_custom"
- Run "azd env set OPENAI_BASE_URL {azure-custom-url}"
- Run "azd up"
```

2024-02-14 18:52 UTC, pamelafox commented on app/backend/app.py
> +            azure_endpoint=os.environ["OPENAI_BASE_URL"],
The only difference in this code is the endpoint, right? In that case, I think it'd be preferred to change the original if to "startswith("azure")" and then alter the endpoint only inside that block. Or are you thinking there'll future differentiation between the setup?

2024-02-14 19:01 UTC, pamelafox commented on infra/main.bicep
> +      OPENAI_BASE_URL: openAiBaseUrl
I think this should be AZURE_OPENAI_BASE_URL or AZURE_OPENAI_CUSTOM_URL, to clarify that it's being used with an Azure client.

2024-02-14 19:02 UTC, pamelafox requested changes
See comments

2024-02-15 16:53 UTC, andredewes commented
> See comments

Fixed both!

2024-02-15 22:39 UTC, pamelafox commented
Great, I will do some test deploys today of both existing environments and a new environment with this change.

2024-02-16 19:38 UTC, pamelafox approved these changes
My deploy went through successfully, so this doesnt introduce regressions in existing environments. Thanks!

2024-02-16 19:38 UTC, merged