enable Azure appinsights/tracing
Azure-Samples/azure-search-openai-demo pull request #415
Opened 2023-07-12 03:33 UTC by kishorerv93

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2023-07-12 03:34 UTC, kishorerv93 commented
@pamelafox  can you review this PR?

2023-07-12 03:41 UTC, kishorerv93 commented
<img width="501" alt="Screenshot 2023-07-11 at 11 38 20 PM" src="https://github.com/Azure-Samples/azure-search-openai-demo/assets/22155528/6244d1fb-b8c9-47b2-a8db-8db4e557120f">

2023-07-12 05:15 UTC, pamelafox commented on app/backend/app.py
> +        abort(404)
can you avoid the whitespace changes on this diff? (i think all these lines are just whitespace changes)

2023-07-12 05:17 UTC, pamelafox commented on app/backend/app.py
> +logger = logging.getLogger(__name__)
Is the logger variable referenced somewhere here? In Flask, its usually recommended to use app.logger:
https://flask.palletsprojects.com/en/2.3.x/logging/

2023-07-12 05:18 UTC, pamelafox commented on app/backend/approaches/chatreadretrieveread.py
> +        # STEP 1: Generate an optimized keyword search query based on the chat history and the last question
Whitespace changes?

2023-07-12 05:19 UTC, pamelafox commented on app/backend/approaches/chatreadretrieveread.py
> +from opencensus.ext.azure.log_exporter import AzureLogHandler
Why does this file use opencensus and the other one uses opentelemetry?

2023-07-12 05:20 UTC, pamelafox requested changes
Please fill out the PR with all the fields, like description.

2023-07-26 23:14 UTC, closed without merging

2023-07-27 16:40 UTC, pamelafox commented
@vrajroutu I see you closed this - are you planning to re-open or make a new PR? I do think AppInsights would be great to support.

2023-07-27 16:41 UTC, vrajroutu commented
@pamelafox; Yes i'm working on submitting a new PR. will be there in a bit :)