Add front-matter needed for Sample browser
Azure-Samples/azure-search-openai-demo pull request #816
Opened 2023-10-17 17:11 UTC by pamelafox

## Purpose

This sample is not currently discoverable in the Azure Samples browser:
https://learn.microsoft.com/en-us/samples/browse/

We'd like all the OpenAI chat sample apps to be indexed there, but that requires adding some YAML to README.md.

Instructions here:

https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main#add-metadata-to-readme

Unfortunately, the YAML will get rendered in the README.md. We've given feedback to the Learn.com that we don't want to have it visible, but for now, we don't see a way to hide it.

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* View readme

2023-10-19 22:51 UTC, chuwik requested changes

2023-10-19 22:51 UTC, chuwik commented on README.md
> +- azure-openai
Can you please add ACS here too?

2023-10-19 23:28 UTC, pamelafox commented on README.md
> +- azure-openai
Yes, great point!

2023-10-20 00:22 UTC, chuwik approved these changes

2023-10-20 00:37 UTC, merged